name: unguided
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter


  mapbox_maps_flutter: ^1.0.0
  permission_handler: ^11.1.0
  geolocator: ^10.0.0
  http: ^1.2.0


assets:
  - assets/pin.png


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
